window.OBS_MASTER = [
  {id:1, title:"Checking Logbook & BPC", role:"LP", default:"YES", type:"YESNO"},
  {id:2, title:"Checking Safety Items & HTC", role:"LP", default:"YES", type:"YESNO"},
  {id:3, title:"Energy Meter & SPM check", role:"LP", default:"YES", type:"YESNO"},
  {id:4, title:"Checking RS Valve working", role:"ALP", default:"YES", type:"YESNO"},
  {id:5, title:"Checking Safety Items & HTC", role:"ALP", default:"YES", type:"YESNO"},
  {id:6, title:"Energy Meter & SPM check & Input", role:"ALP", default:"YES", type:"YESNO"},
  {id:7, title:"Conducting BFT & BPT", role:"LP", default:"YES", type:"YESNO"},
  {id:8, title:"Calling Out Signals", role:"LP", default:"YES", type:"YESNO"},
  {id:9, title:"Use of Mobile Phone", role:"LP", default:"NO", type:"YESNO"},
  {id:10, title:"Micro Sleep", role:"LP", default:"NO", type:"YESNO"},
  {id:11, title:"Exchange of Signals", role:"LP", default:"YES", type:"YESNO"},
  {id:12, title:"Neutral Section Action", role:"LP", default:"YES", type:"YESNO"},
  {id:13, title:"Alertness", role:"LP", default:"VERY GOOD", type:"RATING"},
  {id:14, title:"Standing RS at Danger Signal", role:"ALP", default:"YES", type:"YESNO"},
  {id:15, title:"Calling Out Signals", role:"ALP", default:"YES", type:"YESNO"},
  {id:16, title:"Use of Mobile Phone", role:"ALP", default:"NO", type:"YESNO"},
  {id:17, title:"Micro Sleep", role:"ALP", default:"NO", type:"YESNO"},
  {id:18, title:"Exchange of Signals", role:"ALP", default:"YES", type:"YESNO"},
  {id:19, title:"Formation Check", role:"ALP", default:"YES", type:"YESNO"},
  {id:20, title:"Alertness", role:"ALP", default:"VERY GOOD", type:"RATING"},
  {id:21, title:"Application A9-SA9", role:"LP", default:"YES", type:"YESNO"},
  {id:22, title:"Reverser Neutral", role:"LP", default:"YES", type:"YESNO"},
  {id:23, title:"Headlight Dimming", role:"LP", default:"YES", type:"YESNO_DAY"},
  {id:24, title:"Undergear Check", role:"LP", default:"YES", type:"YESNO"},
  {id:25, title:"Whistle before start", role:"LP", default:"YES", type:"YESNO"},
  {id:26, title:"Ensure A9-SA9", role:"ALP", default:"YES", type:"YESNO"},
  {id:27, title:"Ensure Reverser Neutral", role:"ALP", default:"YES", type:"YESNO"},
  {id:28, title:"Ensure Headlight Dimming", role:"ALP", default:"YES", type:"YESNO_DAY"},
  {id:29, title:"Undergear Check", role:"ALP", default:"YES", type:"YESNO"},
  {id:30, title:"Signal Exchange Before Start", role:"ALP", default:"YES", type:"YESNO"},
  {id:31, title:"Packing After Arrival", role:"LP", default:"YES", type:"YESNO"},
  {id:32, title:"Overall Performance", role:"LP", default:"VERY GOOD", type:"RATING"},
  {id:33, title:"Packing After Arrival", role:"ALP", default:"YES", type:"YESNO"},
  {id:34, title:"Overall Performance", role:"ALP", default:"VERY GOOD", type:"RATING"},
];
